Mykarehealth
lemokami/startupsofkerala pull request #40
Opened 2022-10-25 18:44 UTC by SuvarneshKM

2022-10-25 19:39 UTC, lemokami requested changes
Could you convert the svg file `public/logos/mykarehealth.svg` to png as it affects the display of the image mykarehealth page

2022-10-26 16:12 UTC, SuvarneshKM commented
> Could you convert the svg file `public/logos/mykarehealth.svg` to png as it affects the display of the image mykarehealth page

Done

2022-10-26 16:16 UTC, lemokami approved these changes

2022-10-26 16:17 UTC, merged

2022-10-26 16:17 UTC, lemokami commented
Thank you @SuvarneshKM 👍